### PR TITLE
WP API: Allow calling WP API endpoints

### PR DESCRIPTION
**Pull request by youknowriad**
- Display a switch between WP.COM API and WP API
  - For now we can type custom requests but we can not select endpoints yet

capture d ecran 2016-10-20 a 9 17 00 am

The API describing the endpoints is not the same between WP-API and WP.COM, so we may need an adapter in order to display the endpoints correctly

### CODE REVIEW

**Comment by timmyc** [comment]
@youknowriad is there any chance we can key off of the api version drop down to change the base path?  So far what we have done in wpcom.js and calypso is to use the `apiNamespace` as how we change the base path between wpcom API requests and WP-API api requests.

So perhaps we can use the existing version drop down in the developer console and add the WP-API namespaces there?  `wp/v2` and `wpcom/v2`.  What do you think?

**Comment by youknowriad** [comment]
@timmyc In my opinion It's better to leave it outside the version dropdown, because the namespace is not the only difference between the two APIs.

There's a different "discover" request based on the API, parsing the results of the the "discover endpoints" api call is also very different between the two APIs. To mark those differences, I prefer to keep another dropdown but merging is possible.

(more details on these differences on my other PR https://github.com/Automattic/rest-api-console2/pull/20 which relies on this one :) )

**Comment by nylen** [comment]
Rebased after merge of #19.

**Comment by nylen** [comment]
I'll merge this and continue review on #21.

**Pull request merged**
